### PR TITLE
title change

### PR DESCRIPTION
**Pull request by Tadii3108**

### CODE REVIEW

**Comment by Sbonelo01** [comment]
Project is well done. works great and is functional

**Review by Sbonelo01 — COMMENTED** [review]
The name change is not that nessessary, but it makes sense

**Comment by Tadii3108** [comment]
> The name change is not that nessessary, but it makes sense

Oh yes sure, but the name change was just a minor change for me to be able to create a pull request otherwise it would've been the initial title

**Comment by Tadii3108** [comment]
> Project is well done. works great and is functional

Thank you!

**Pull request merged**
